name: CI

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run DeteKt check
        uses: natiginfo/action-detekt-all@1.23.8
        with:
          args: --config .detekt.yaml

      - name: markdown-lint
        uses: DavidAnson/markdownlint-cli2-action@v20.0.0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.3.1
        with:
          gradle-version: 8.4

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd python
          poetry install

      - name: Run tests and collect coverage
        run: |
          cd python
          poetry run coverage run -m pytest -k 'not prob1' .
          poetry run coverage report -m
